name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      working-directory: ./src/WebClient
      run: dotnet restore
    - name: Build
      working-directory: ./src/WebClient
      run: dotnet build --no-restore
    - name: Test
      working-directory: ./src/Test
      run: dotnet test --no-build --verbosity normal
